### ISSUE TITLE
Check user type

### ISSUE THREAD

**Issue by allerpi** [ac-datamatics/ccp-embed#6]
Find a way to know if the user logging in is an agent, call center manager, or admin

**Comment by edvilme** [comment]
Using `connectListener.agent.getPermissions()`, we can have an array of the user permissions. Otherwise we could just fetch that data from a REST API on our own backend.

<img width="510" alt="image" src="https://user-images.githubusercontent.com/5952839/168315619-153129eb-4594-44d0-9b95-e542dc2c3cee.png">
